In [1]:
import numpy as np

In [3]:
tn = ['G', 'B',
      'B', 'G',
      'B', 'B']
n=100
generations=1000
rounds=10
fr=(0.8, 'CD')
init_good=0.5
mu=0.02
epsilon=0.01
e_rep=0
e_act=0
c=3
b=9
alpha=1
beta=4
communication=100
com_mode=1
init_correlation=0

In [149]:
def r_to_num(r):
    return 0 if r == 'G' else 1

def s_to_num(s):
    match s:
        case 'C':
            return 0
        case 'D':
            return 1
        case 'P':
            return 2

def _set_strategy(n, fr):
    strategy = np.zeros((n, 2), dtype=np.uint8)
    th = int(n * fr[0])

    # megadott %-ú ágenshez beállítom a kezdetben többségi viselkedési szabályt
    strategy[:th, 0] = s_to_num(fr[1][0])
    strategy[:th, 1] = s_to_num(fr[1][1])
    # maradék ágensek véletlenszerű cselekvési szabályt kapnak
    strategy[th:, :] = np.random.randint(0, 3, size=(n - th, 2))

    return strategy

In [150]:
strategy = _set_strategy(n, fr)

In [77]:
public_norm = np.array([r_to_num(t) for t in tn], dtype=np.uint8).reshape(3, 2)

In [79]:
public_norm

array([[0, 1],
       [1, 0],
       [1, 1]], dtype=uint8)

In [95]:
donoridx = 20
recipientidx = 45
donor_action = 2     # coperal

In [109]:
reputation

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 1, 0]], shape=(100, 100), dtype=uint8)

In [114]:
parok = np.random.permutation(n).reshape(-1, 2)

In [136]:
rec_hirnev = 1

In [154]:
donoridx

20

In [157]:
# A hibákat XOR-ral tudjuk kezelni: a rec_hirnev 0<->1 átfordul, ha hiba van
donor_action = strategy[donoridx][np.bitwise_xor(rec_hirnev, (np.random.rand() <= e_rep))]

In [158]:
donor_action

np.uint8(2)

In [155]:
strategy[20]

array([0, 1], dtype=uint8)

In [156]:
strategy[80]

array([0, 2], dtype=uint8)

In [174]:
donoridx = 20

In [175]:
donor_action = strategy[donoridx][np.bitwise_xor(rec_hirnev, (np.random.rand() <= e_rep))]

In [176]:
donor_action

np.uint8(1)

In [177]:
if np.random.rand() > e_rep: # ha NINCSEN hiba
    donor_action = strategy[donoridx][0] if (rec_hirnev == 0) else strategy[donoridx][1]
else:
    donor_action = strategy[donoridx][0] if (rec_hirnev == 1) else strategy[donoridx][1]

In [178]:
donor_action

np.uint8(1)

In [179]:
(np.random.rand() <= e_act)

False

In [180]:
np.bitwise_xor(donor_action, (np.random.rand() <= e_act))

np.uint8(1)

In [182]:
reputation

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 1, 0]], shape=(100, 100), dtype=uint8)

In [206]:
np.random.choice(np.arange(0, n), 3, replace=False)

array([78, 38, 28])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [222]:
matrix = np.random.randint(0, 100, (2, 3))

In [ ]:
np.random.choice()

In [ ]:
np.arange(0, n, )

In [219]:
rand_matrix = np.random.randint(0, n, ()

ValueError: low >= high

In [ ]:
rand_matrix

In [213]:
rand_matrix = 

In [216]:
rand_matrix

array([[0.27205858, 0.23732663, 0.40268952, ..., 0.81505155, 0.1042801 ,
        0.24695242],
       [0.49812111, 0.03833008, 0.40773721, ..., 0.54203497, 0.76406831,
        0.87314487],
       [0.04697233, 0.94823014, 0.11003324, ..., 0.75864305, 0.78551691,
        0.94831969],
       ...,
       [0.87702503, 0.0916341 , 0.33866023, ..., 0.28355447, 0.49494243,
        0.34388833],
       [0.17418469, 0.12765006, 0.30148623, ..., 0.50906588, 0.36100239,
        0.6753662 ],
       [0.11512703, 0.33495142, 0.70709196, ..., 0.90418455, 0.79929717,
        0.12375688]], shape=(10000, 100))

In [217]:
np.argsort(rand_matrix, axis=1)

array([[ 3, 28, 34, ..., 70, 90, 96],
       [49, 83,  1, ..., 33, 95, 28],
       [58, 12, 50, ..., 89, 48, 16],
       ...,
       [84, 63, 67, ..., 11, 47, 16],
       [12, 89, 41, ..., 47, 27, 13],
       [15, 38, 72, ..., 16, 40, 71]], shape=(10000, 100))

In [261]:
rep

array([[0, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0]], shape=(100, 100), dtype=uint8)

In [259]:
vszamok = np.argsort(np.random.rand(n*communication, n), axis=1)[:, :3]

In [260]:
vszamok

array([[70, 47, 35],
       [20, 41, 45],
       [94,  2, 28],
       ...,
       [68, 94, 10],
       [67,  4, 52],
       [37, 40,  7]], shape=(10000, 3))

In [ ]:
# reputation[l][n] = reputation[m][n]
reputation[vszamok]

In [267]:
# l
vszamok[:, 0]

array([70, 20, 94, ..., 68, 67, 37], shape=(10000,))

In [268]:
# m
vszamok[:, 1]

array([47, 41,  2, ..., 94,  4, 40], shape=(10000,))

In [269]:
# n
vszamok[:, 2]

array([35, 45, 28, ..., 10, 52,  7], shape=(10000,))

In [273]:
# az informátor vélemény listája minden loop-ban
reputation[vszamok[:, 1]]

array([1, 1, 0, ..., 0, 0, 1], shape=(10000,), dtype=uint8)

In [274]:
# az informátor vélemény listája minden loop-ban, de csak n témaszemélyről
reputation[vszamok[:, 1], vszamok[:, 2]]

array([1, 1, 0, ..., 0, 0, 1], shape=(10000,), dtype=uint8)

In [279]:
# a hallgató l véleménye n témaszemélyről
reputation[vszamok[:, 0], vszamok[:, 2]]

array([1, 1, 1, ..., 1, 1, 0], shape=(10000,), dtype=uint8)

In [285]:
reputation[37, 7]

np.uint8(0)

In [286]:
reputation[vszamok[:, 0], vszamok[:, 2]] = reputation[vszamok[:, 1], vszamok[:, 2]]

In [ ]:
reputation[vszamok[:, 0], vszamok[:, 2]] = reputation[vszamok[:, 1], vszamok[:, 2]]

In [287]:
reputation[vszamok[:, 0], vszamok[:, 2]]

array([1, 1, 0, ..., 0, 0, 1], shape=(10000,), dtype=uint8)

In [298]:

mask = reputation[vszamok[:, 0], vszamok[:, 1]] == 0  # l hallgaó véleménye az m informátorról, csak azok a sorok ahol good
reputation[vszamok[:, 0], vszamok[:, 2]][mask] = reputation[vszamok[:, 1], vszamok[:, 2]][mask]

In [299]:
vszamok = np.argsort(np.random.rand(n * communication, n), axis=1)[:, :3]  # (l,m,n), len=n*communication

In [300]:
vszamok

array([[73, 70, 17],
       [91, 59, 87],
       [71, 24, 38],
       ...,
       [69,  4, 16],
       [48, 13, 46],
       [65, 77, 47]], shape=(10000, 3))

array([1, 0, 0, ..., 1, 0, 1], shape=(4858,), dtype=uint8)

In [301]:
%time
# miutám minden pár játszott jön a kommunikációs kör
vszamok = np.argsort(np.random.rand(n * communication, n), axis=1)[:, :3]  # (l,m,n), len=n*communication

if com_mode == 1:
    reputation[vszamok[:, 0], vszamok[:, 2]] = reputation[vszamok[:, 1], vszamok[:, 2]]
elif com_mode == 2:
    mask = reputation[vszamok[:, 0], vszamok[:, 1]] == 0  # l hallgaó véleménye az m informátorról, csak azok a sorok ahol good
    reputation[vszamok[:, 0], vszamok[:, 2]][mask] = reputation[vszamok[:, 1], vszamok[:, 2]][mask]
else:
    raise Exception('A com_mode változó értéke csak 1 vagy 2 lehet!')

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 5.01 μs


In [302]:
vszamok = np.random.randint(0, n, size=(n * communication, 3))

In [303]:
vszamok

array([[ 2,  5, 17],
       [ 6, 25, 12],
       [ 5, 37, 75],
       ...,
       [41,  5, 80],
       [69, 70, 52],
       [ 6, 61, 98]], shape=(10000, 3))

In [304]:
parok = np.random.permutation(n).reshape(-1, 2)

In [305]:
parok

array([[36,  9],
       [56,  4],
       [60, 58],
       [27, 26],
       [51,  1],
       [ 7, 19],
       [70, 30],
       [67, 10],
       [71, 21],
       [24, 76],
       [61, 73],
       [23, 79],
       [63, 18],
       [96, 44],
       [11, 49],
       [17, 46],
       [99, 52],
       [64, 86],
       [77, 57],
       [ 5, 42],
       [59, 28],
       [90, 89],
       [80, 38],
       [ 2, 78],
       [66, 29],
       [65, 12],
       [84, 68],
       [92, 82],
       [81, 40],
       [94, 97],
       [13, 93],
       [45, 22],
       [16, 55],
       [48, 62],
       [14, 54],
       [72, 33],
       [50, 95],
       [69, 83],
       [39, 98],
       [ 8, 37],
       [91, 74],
       [31, 15],
       [34, 43],
       [32, 75],
       [87,  3],
       [85, 47],
       [ 0,  6],
       [41, 25],
       [53, 20],
       [88, 35]])

In [306]:
rec_hirnev = reputation[parok[:, 0], parok[:, 1]]

In [326]:
rec_hirnev

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0], dtype=uint8)

In [368]:
rec_hirnev

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0], dtype=uint8)

In [382]:
np.bitwise_xor(rec_hirnev, (np.random.rand(int(n/2)) <= e_rep)) # == rec_hirnev

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0], dtype=uint8)

In [390]:
parok = np.random.permutation(n).reshape(-1, 2)

In [391]:
rec_hirnev = reputation[parok[:, 0], parok[:, 1]]

In [392]:
donor_action = strategy[parok[:, 0]][np.arange(int(n/2)), np.bitwise_xor(rec_hirnev, (np.random.rand(int(n/2)) <= e_rep))]

In [398]:
times_of_cooperation = donor_action[donor_action == 0].size